### ISSUE TITLE
找不到core_dataout.pri

### ISSUE THREAD

**Issue by Alan-li** [feiyangqingyun/QWidgetExe#1]
找不到对应的源代码导入。

**Comment by Alan-li** [comment]
能提供下源码吗？感谢。

**Comment by feiyangqingyun** [comment]
Qt编写的一些组件的可执行文件，包括对应的说明文档、运行截图等，项目都是商业级别，如有需要完整源码或者定制功能请联系购买，QQ：517216493 微信：feiyangqingyun 推荐加微信。
